language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE test_ireporter;' -U postgres 

#Command to run tests
script:
  - nosetests --with-coverage --cover-tests
  - coverage report

after_success:
  - coveralls