FORMAT: 1A
HOST: https://ireporterch3.herokuapp.com/

# Ireporter

IReporter enables any/every citizen to bring any form of corruption to the notice of appropriate authorities and the general public. Users can also report on things that needs government intervention

## Signup user [/api/v1/users]

### Create user account [POST]

You can create a store attendant account by sending a json request with a username, email and a password.
The username must not contain any white space and the email must be a valid email.

+ Request (application/json)

    + Headers

            Authorization: 'user token'

    + Body

            {
                "firstname":"zeng",
                "lastname":"leng",
                "othernames":"lenpen",
                "email":"zeng@gmail.com",
                "phonenumber":2567430531,
                "username":"leng",
                "password":"123Abc123456"
            }
            
+ Response 201 (application/json)
            
            {
                "data": {
                    "email": "zeng@gmail.com",
                    "firstname": "zeng",
                    "lastname": "leng",
                    "othernames": "lenpen",
                    "phonenumber": 2567430531,
                    "username": "leng"
                        },
                "message": "Your Account was created successfuly",
                "status": 201
            }
            
+ Response 400 (application/json)

            {
                'status': 400,
                'error': 'A required field is either missing or empty'
            }
            
+ Response 400 (application/json)

            {
                'status': 400,
                'error': 'Name must be a string and must not contain spaces'
            }
            
+ Response 400 (application/json)

            {
                'status': 400,
                'error': 'Only numbers are allowed for the phonenumber field'
            }
            
+ Response 400 (application/json)

            {
                'status': 400,
                'error': 'Invalid email'
            }
            
+ Response 400 (application/json)

            {
                'status': 400,
                'error': 'Password must be atleast 8 characters and should have atleast one number and one capital letter'
            }
            
+ Response 400 (application/json)

            {
                'status': 400,
                'error': 'User account already exists'
            }

# login user [/api/v1/users/login]

### login user [POST]

Login user to access the system

+ Request (application/json)

    + Body

            {
                "email":"zeng@gmail.com",
                "password":"123Abc123456"
            }
            
+ Response 200 (application/json)

    + Body
            {
            'status': 200, 'access_token': 'token,
            'message': 'You are now loggedin'
            }
            
+ Response 403 (application/json)

    + Body
            {
            'status': 403,
            'error': 'Wrong email or password'
            }

            
# post intervention [/api/v1/interventions]

### create an intervention record [POST]

create an intervention record. Please note that only a registered user can perform this action.
An admin can not perform this action

+ Request (application/json)

    + Headers

              Authorization: 'user token'


    + Body
              { 
                "incident_type":"intervention",
                "location":[4.66, 1.55],
                "comment": "pooor ddddd",
                "image":{"title":"sassaqwqwq","url":"sasasdsdd"},
                "video":{"title":"sassaqwqwq","url":"sasasdsdd"}
              }
              
+ Response 201 (application/json)

    + Body
           {
            "data": {
                "comment": "pooor d",
                "createdon": "Fri, 25 Jan 2019 10:25:56 GMT",
                "image": {
                    "title": "sassaqwqwq",
                    "url": "sasasdsdd"
                },
                "incident_location": [
                    4.66,
                    1.54
                ],
                "record_type": "intervention",
                "status": "Draft",
                "video": {
                    "title": "sassaqwqwq",
                    "url": "sasasdsdd"
                }
            },
            "message": "created intervention record successfuly",
            "status": 201
            }
            
+ Response 400 (application/json)

    + Body
            {
            'status': 400,
            'error': 'A required field is either missing or empty'
            }
            
+ Response 400 (application/json)

    + Body 
            {'status': 400,
             'error': 'type must a string and must be red-flag or intervention'
            }
            
+ Response 400 (application/json)

    + Body 
            {
            'status': 400,
            'error': 'Location field only takes in a list of valid Lat and Long cordinates'
            }

+ Response 400 (application/json)

    + Body 
            {
            'status': 400,
            'error': 'comment must be a string'
            }

+ Response 400 (application/json)

    + Body
            {
            'status': 400,
            'error': 'Image url or title or video url or title is invalid'
            }

# Get all interventions [/api/v1/interventions]

### Get all interventions [GET]

+ Request (application/json)

     + Headers

              Authorization: 'user token'
              
+ Response 200 (application/json)

    + Body
            {
            "data": [
                {
                    "comment": "pooor ddddd",
                    "createdby": "1",
                    "createdon": "2019-01-24 22:43:04.152603",
                    "image": {
                        "title": "sassaqwqwq",
                        "url": "sasasdsdd"
                    },
                    "incident_location": "[4.66, 1.55]",
                    "incidentid": 8,
                    "record_type": "intervention",
                    "status": "resolved",
                    "video": {
                        "title": "sassaqwqwq",
                        "url": "sasasdsdd"
                    }
                },
                {
                    "comment": "pooor d",
                    "createdby": "12",
                    "createdon": "2019-01-25 10:25:56.077019",
                    "image": {
                        "title": "sassaqwqwq",
                        "url": "sasasdsdd"
                    },
                    "incident_location": "[4.66, 1.54]",
                    "incidentid": 9,
                    "record_type": "intervention",
                    "status": "Draft",
                    "video": {
                        "title": "sassaqwqwq",
                        "url": "sasasdsdd"
                    }
                }
            ],
            "status": 200
            }

# Get one intervention [/api/v1/interventions]

### Get one intervention [GET]

+ Request (application/json)

    + Headers

             Authorization: 'user token'
              
+ Response 200 (application/json)

    + Body   
         {
        "data": {
            "comment": "pooor ddddd",
            "createdby": "1",
            "createdon": "2019-01-24 22:43:04.152603",
            "image": {
                "title": "sassaqwqwq",
                "url": "sasasdsdd"
            },
            "incident_location": "[4.66, 1.55]",
            "incidentid": 8,
            "record_type": "intervention",
            "status": "rejected",
            "video": {
                "title": "sassaqwqwq",
                "url": "sasasdsdd"
            }
        },
        "status": 200
            }
 
   
# Edit intervention record location [/api/v1/interventions/2/incident_location]

### Edit intervention location  [PATCH]

+ Request (application/json)

    + Headers
    
            Authorization: 'user token'
             
    + Body
            {
             "location": [333.33, 44.333]
            }
            
+ Response 200 (application/json)

    + Body
          {
            "data": {
                "comment": "pooor d",
                "createdby": "12",
                "createdon": "2019-01-25 10:25:56.077019",
                "image": {
                    "title": "sassaqwqwq",
                    "url": "sasasdsdd"
                },
                "incident_location": "[33.33, 444.7]",
                "incidentid": 9,
                "record_type": "intervention",
                "status": "Draft",
                "video": {
                    "title": "sassaqwqwq",
                    "url": "sasasdsdd"
                }
            },
            "message": "Updated intervention record's location",
            "status": 200
          }

    
+ Response 200 (application/json)

    + Body   
          {
            "message": "incident record not found",
            "status": 200
         }

+ Response 400 (application/json)

    + Body
          {
            "error": "You cannot change the location while the incident status is not Draft",
            "status": 400
         }
         
# Edit intervention record comment [/api/v1/interventions/2/incident_comment]

### Edit intervention comment [PATCH]

+ Request (application/json)

    + Headers
    
            Authorization: 'user token'
    
    + Body
          {
           "comment": "poor"
          }

+ Response 200 (application/json)

    + Body
          {
            "data": {
                "comment": "pooor d",
                "createdby": "12",
                "createdon": "2019-01-25 10:25:56.077019",
                "image": {
                    "title": "sassaqwqwq",
                    "url": "sasasdsdd"
                },
                "incident_location": "[33.33, 444.7]",
                "incidentid": 9,
                "record_type": "intervention",
                "status": "Draft",
                "video": {
                    "title": "sassaqwqwq",
                    "url": "sasasdsdd"
                }
            },
            "message": "Updated intervention record's comment",
            "status": 200
          }  
            
+ Response 200 (application/json)

    + Body   
          {
            "message": "incident record not found",
            "status": 200
         }
         
+ Response 400 (application/json)

    + Body
          {
            "error": "You cannot change the location while the incident status is not Draft",
            "status": 400
            }
    
# Delete intervention record [/api/v1/interventions/4]

### Delete intervention  [DELETE]

+ Request (application/json)

    + Headers
    
            Authorization: 'user token'
            
+ Response 200 (application/json)

    + Body
          {
            "message": "intervention record has been deleted",
            "status": 200
         }

# Edit intervention record status [/api/v1/interventions/1/status]

### Edit intervention status [PATCH]

+ Request (application/json)

    + Headers
    
            Authorization: 'user token'
            
    + Body
          {"status": "rejected"}
            
+ Response 200 (application/json)

    + Body
          {
            "data": {
                "comment": "pooor d",
                "createdby": "12",
                "createdon": "2019-01-25 10:25:56.077019",
                "image": {
                    "title": "sassaqwqwq",
                    "url": "sasasdsdd"
                },
                "incident_location": "[33.33, 444.7]",
                "incidentid": 9,
                "record_type": "intervention",
                "status": "rejected",
                "video": {
                    "title": "sassaqwqwq",
                    "url": "sasasdsdd"
                }
            },
            "message": "intervention record's status was successfuly updated",
            "status": 200
        }
          
+ Response 200 (application/json)

    + Body
          {
            "message": "incident record not found",
            "status": 200
          }
          
+ Response 400 (application/json)
    
    + Body
          {
            "error": "incident_id must be a valid number",
            "status": 400
         }